### ISSUE TITLE
Не отображается общий список всех друзей пользователей

### ISSUE THREAD

**Issue by disovi** [nikGogolev/vk-friends-app#1]
Сейчас отображаются только друзья из исходного списка, необходимо отобразить всех друзей выбранных пользователей

![image](https://user-images.githubusercontent.com/705617/182209023-746ad50d-e879-4e2a-850a-1a97c2aa07ad.png)

**Comment by nikGogolev** [comment]
@disovi Исправлено. Изначально неверно трактовал задание

**Comment by disovi** [comment]
@nikGogolev возможно, вы не задеплоили новую версию на github-pages, сейчас по-прежнему результат, как на скриншоте выше

**Comment by nikGogolev** [comment]
@disovi задеплоил, но мне пришлось сбросить кэш в браузере, чтобы он новую версию съел

**Comment by disovi** [comment]
@nikGogolev спасибо, это помогло
